SCE-Development/git-workshop

index.html
styles.css

Changes the background color of the tab bar to blue

change tab color to blue 

---

index.html

I heard there would be free snacks.

Let's team up. I know the chemistry, you know the business.

---

index.html

changed the text in header 1 in index.html

Add "Show my changes here" to "why git?" line

---

styles.css

change title to blue and body to red
Before:
After:

change title to blue

---

index.html

I'm making my contribution, change it if you want.

Change something

---

index.html
recipe/pizza.html

This is the pizza recipe website:

added a pizza recipe to the website (Task #1)

---

recipe/egg.html

add a twist to the egg recipe

---

index.html
recipe/burger.html

Add recipe for burger

---

index.html
recipe/quesadillas.html

Sujan: Added quesadillas recipe (Task 1)

---

recipe/burger.html

Task 2: Modify an Existing Recipe

Viet: Changed Burger Recipe (Task 2)

---

recipe/egg.html

Changed Sesame Oil to Butter. I find it tastes better, albeit more unhealthy.

Geo/20250529 Make Egg American

---

index.html
recipe/waffle.html

This PR is my completion of Task 1 of the Git workshop, where I added a recipe for protein waffles to the project.

Adarsh: Added Waffle Recipe (Task 1)

---

recipe/greatestsandwichofalltime.html

merge #40 first!
added a critique to the old sandwich recipe

PR 3: Added food critique

---

index.html
recipe/cereal.html

Added cereal.html recipe file and updated index.html with a link to the new recipe.

Add cereal recipe

---

index.html
recipe/bimbibap.html

add bimbibap

---

index.html
recipe/eggdropsoup.html

add egg drop soup recipe

---

recipe/epic.html

added an important step to the butter toast

make the epic even more epic

---

index.html
recipe/tiramisu.html

added the tiramisu recipe
added a link into index.html
attached screen shot

Sean added tiramisu recipe 

---

recipe/coffee.html

Added optional ingredients to coffee recipe

---

recipe/flan.html

david_nguyen/6-1-2025_add-food-critic

---

recipe/flan.html

added the flan recipe
added a link into index.html
attached screen shot

david_nguyen/6-1-2025_added flan recipe

---

index.html
recipe/cereal.html

Add food critic review section to recipe/cereal.html
Merge #44 first!

add cereal critique

---

recipe/lemonade.html

updated lemonade recipe to remove ice, merge PR#2 First

evanf/20250603 PR#2 updated recipe

---

index.html
recipe/waffle.html

Merge #28 first!!
This PR adds a food critic review section to the waffle recipe

Adarsh: Added food critic review (Task #3)

---

index.html
recipe/lemonade.html

Requires merge #46 first
Task 3: Add Food Critic Section

Viet: Added Food Critic Section to Lemonade Recipe (Task #3)

---

recipe/popcorn_chicken.html

Add review to popcorn chicken recipe

---

index.html
recipe/friedrice.html

added fried rice

---

recipe/egg.html

added my recipe under the recipe folder called beerchickenstew.html
added redirect link in index.html
great meal to make when you're hosting, or wanna bring something to a potluck. people always love it. obviously not vegan or vegetarian cause chicken and bacon and stuff.

added chicken stew recipe

---

recipe/greatestsandwichofalltime.html

Add review to greatest sandwhich

---

index.html
recipe/oatmeal.html

add oatmeal recipe

---

recipe/roticanai.html

Add food review to roti canai

---

index.html
recipe/roticanai.html

Added roti canai recipe

---

recipe/flan.html

Updated flan recipe

---

index.html
recipe/coffee.html

Self explanatory title.
Screenshot:

Added Coffee Recipe

---

index.html
recipe/fugu.html

add food critic review to fugu recipe

---

index.html
recipe/simpleomlette.html

Add simple omlette recipe

---

recipe/simpleomlette.html

Added food critic review

---

index.html
recipe/afghanpasta.html

Add Afghan Pasta recipe

---

recipe/hydratedwater.html

Updated Water Recipe

---

index.html
recipe/padkrapao.html

Added a Pad Kra Pao recipe

---

recipe/egg.html

modified egg recipe

---

index.html
recipe/thaitea.html

Embotic-Wayne/20250706 Add-ThaiTea-recipe

---

index.html
recipe/lentilsoup.html

Add lentilsoup.html and edit index.html
